version: "0.2"
language: en-GB,en-US
ignorePaths:
  - package-lock.json
  - node_modules
  - vscode-extension
  - .git/objects
  - .vscode
  - .vscode-insiders
  - .vscode\extensions\*
  - .gitignore
  - .dockerignore
dictionaryDefinitions: []
dictionaries: []
words:
  - elif
  - pytest
  - rando
  - sdist
  - xfail
ignoreWords: []
import: []
