name: Test Poetry

on:
  push:
    branches:
      - master
  # Run build manually from the Actions tab, will be tagged with branch name
  workflow_dispatch:

permissions: {}

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # Get repo, python, and poetry
      - name: Checkout the repository
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.2
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Install Poetry plugins
        run: poetry self add poetry-plugin-export

      - name: List Poetry plugins
        run: poetry self show plugins

      - name: Generate requirements.txt
        run: poetry export --only main -f requirements.txt -o requirements.txt