name: Pull Request Labler
on:
  pull_request:
    types:
     - opened
     - reopened
permissions:
  pull-requests: write

jobs:
  dependabot-metadata:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Get Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Print package ecosystem
        run: echo ${{ steps.metadata.outputs.package-ecosystem }}
      
      - name: Print dependency type
        run: echo ${{ steps.metadata.outputs.dependency-type }}
    
    outputs:
      package-ecosystem: ${{ steps.metadata.outputs.package-ecosystem }}
      dependency-type: ${{ steps.metadata.outputs.dependency-type }}

  debug:
    runs-on: ubuntu-latest
    steps:
      - run: echo github.ref=${{ github.ref }}
      - run: echo github.ref_name=${{ github.ref_name }}
      - run: echo github.event.pull_request.labels.*.name=${{ join(github.event.pull_request.labels.*.name, ', ') }}
      - run: echo github.event.pull_request.base=${{ join(github.event.pull_request.base, ', ') }}
      - run: echo github.head_ref=${{ github.head_ref }}

  label-dependabot-python:
    # Python Dependencies
    runs-on: ubuntu-latest
    # github.actor == 'dependabot[bot]' &&  
    if: contains(github.event.pull_request.labels.*.name, 'python')
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: "Python: dependencies:production"
        if: contains(github.head_ref, 'development-') == false
        run: gh pr edit "$PR_URL" --add-label "dependencies:production"

      - name: "Python: dependencies:development"
        if: contains(github.head_ref, 'development-')
        run: gh pr edit "$PR_URL" --add-label "dependencies:development"

  label-dependabot-github-actions:
    # GitHub Actions Dependencies
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'github_actions')
    env:
      GH_TOKEN: ${{ github.token }}
    steps:        
      - name: "GitHub Actions: dependencies:development"
        run: gh pr edit "$PR_URL" --add-label "dependencies:development"
