name: Pull Request Validation
on:
  pull_request:
    types:
     - opened
     - reopened

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - run: echo github.ref= ${{ github.ref }}
      - run: echo github.ref_name= ${{ github.ref_name }}
      - run: echo github.event.pull_request.labels.*.name= ${{ join(github.event.pull_request.labels.*.name, ', ') }}
      - run: echo github.event.pull_request.base= ${{ join(github.event.pull_request.base, ', ') }}
      - run: echo github.head_ref= ${{ github.head_ref }}

  label-dependabot-python:
    # Python Dependencies
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write

    # github.actor == 'dependabot[bot]' &&  
    if: contains(github.event.pull_request.labels.*.name, 'python')
    steps:
      # https://github.com/GitHubSecurityLab/actions-permissions/tree/main/monitor
      - uses: GitHubSecurityLab/actions-permissions/monitor@v1
        with:
          config: ${{ vars.PERMISSIONS_CONFIG }}

      - name: "Python: dependencies:production"
        uses: MakarovAleksey/add-labels@v1
        if: contains(github.head_ref, 'development-') == false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          labels: dependencies:production

      - name: "Python: dependencies:development"
        uses: MakarovAleksey/add-labels@v1
        if: contains(github.head_ref, 'development-')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          labels: dependencies:development

  label-dependabot-github-actions:
    # GitHub Actions Dependencies
    runs-on: ubuntu-latest
    if: contains(github.head_ref, 'github-actions')
    steps:        
      - name: "GitHub Actions: dependencies:development"
        uses: MakarovAleksey/add-labels@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          labels: |
            dependencies:development
            invalid
