name: Python Tests
on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
  push:
    branches:
      - master

jobs:
  checkout-setup-poetry:
    # Setup Repository, Python & Poetry
    uses: lunapurplesunshine/test-repo/.github/workflows/python-setup-poetry.yml@master

  linting-and-format:
    runs-on: ubuntu-latest
    needs: checkout-setup-poetry
    steps:

      # Run linting, formatting, etc.
      # if condition: success() || failure() is used to ensure all steps run, even if one fails
      - name: Lint with Ruff
        run: poetry run ruff check ./randopy tests/

      - name: Format with Black
        uses: cytopia/docker-black@0.11
        if: success() || failure()
        with:
          path: .

      - name: Format with isort
        uses: isort/isort-action@v1.1.0
        if: success() || failure()
        with:
          configuration: "--check-only --diff --profile black"

  pytest:
    runs-on: ubuntu-latest
    needs: checkout-setup-poetry
    steps:
      # Run python tests
      - name: Run pytest
        uses: pavelzw/pytest-action@v2.1.3
        with:
          custom-pytest: poetry run pytest
          verbose: true
          job-summary: true
          report-title: Pytest Report
          emoji: true
          custom-arguments: -r a
          click-to-expand: true
