name: Build & Publish Docker Image

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

permissions: {}

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
        # Get repo, python, and poetry
        - name: Checkout the repository
          uses: actions/checkout@v4
    
        - name: Test DNS resolution
          run: echo "$(dig ${{ secrets.PRIVATE_REGISTRY_URL }})"

        - name: Connect to Tailscale
          uses: tailscale/github-action@v2
          with:
            oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
            oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
            tags: tag:ci

        - name: Test Tailscale IP ping
          run: ping ${{ secrets.PRIVATE_REGISTRY_IP }}""
    
        - name: Test DNS resolution
          run: echo "$(dig ${{ secrets.PRIVATE_REGISTRY_URL }})"
        
        - name: Test Tailscale URL ping
          run: ping ${{ secrets.PRIVATE_REGISTRY_URL }}""

        - name: Login to Private Docker Registry via Tailscale
          uses: docker/login-action@v3
          with:
            registry: ${{ secrets.PRIVATE_REGISTRY_URL }}
            username: ${{ secrets.PRIVATE_REGISTRY_USERNAME }}
            password: ${{ secrets.PRIVATE_REGISTRY_PASSWORD }}
